// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
namespace Kewb
{
	public interface Magic
	{
		string Name { get; set; }
		int GemUsage { get; set; }
		string GameName { get; set; }
		void Execute();
	}
}

