// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using UnityEngine;

namespace Kewb
{
	[XmlRoot("Languages")]
	public class StringContainer
	{


		[XmlArray("Strings"),XmlArrayItem("String")]
		public List<LanguageString> Strings = new List<LanguageString> ();

		public static StringContainer Load() 
		{
			var serializer = new XmlSerializer (typeof(StringContainer));

			var langPath = Application.dataPath + GameManager.Instance.LANGPATH + "language-" + GameManager.Instance.LanguageCode + ".xml";

			using(var stream = new FileStream(langPath, FileMode.Open))
			{
				return serializer.Deserialize(stream) as StringContainer;
			}
		}

		public static string GetString(int page, int key)
		{
			var allStrings = Load ();
			var theString = String.Empty;

			foreach (LanguageString item in allStrings.Strings) {
				if (item.Page == page.ToString() && item.Key == key.ToString()) {
					theString = item.Value;
				}
			}

			return theString;
		}
	}


}